googleapis/nodejs-spanner

- src/transaction.js
- test/transaction.js
Closes https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2673
> use retry info 

- system-test/spanner.js
*Leftover work from #66*
The instance methods we removed were still being used in the system tests.
> Remove custom type instance method usage from system tests.

- .circleci/config.yml
I hate it when you cannot make sure the samples tests run before you merge. Here is the fix, I remember fixing the same thing for the other repo a few weeks ago after I made the same mistake.
> fix path to api key

- package.json
- src/codec.js
- src/partial-result-stream.js
- src/row-builder.js
- src/table.js
- src/transaction-request.js
- system-test/spanner.js
- test/codec.js
- test/partial-result-stream.js
- test/row-builder.js
Fixes #80
When `toJSON()` is called on a Row object, Float64 and Int64 values will now be returned as a JavaScript Number:
```js
var values = row.toJSON()
values.numUsers; // 8
```
> Return un-wrapped Float and Ints by default.

- src/row-builder.js
- test/row-builder.js
Fixes #95
Simple validation. In case Rowbuilder.formatValue receives 'NULL_VALUE' as value, which applies to all types, return null as value for that field.
Unit test were also included in this PR
> Changes RowBuilder.formatValue to return null in case value is 'NULL_VALUE'

- src/transaction.js
- test/transaction.js
> better error handling for ending transactions

- .circleci/config.yml
- package.json
- samples/package.json
- samples/system-test/util/circleci_wait.js
I know it might be not the right way to approach the problem but I have serious concerns that running more than one instance of sample tests for Spanner will break. I'm not sure if it's possible to fix the test fast enough (I thought that changing the instance ID to something unique should help, but something is still wrong), so I suggest having this wait as a temporary might-be-a-solution. 
If we notice it does not help, we can revert it back.
> chore: serialize sample tests execution

- src/database.js
- src/partial-result-stream.js
- src/transaction-request.js
- system-test/spanner.js
- test/database.js
- test/partial-result-stream.js
- test/transaction-request.js
Fixes #27 
Provide `options.toJSON = true` to `database.run`, `table.read`, and `table.createReadStream`, and all returned rows will already have had `toJSON` called on them.
```js
table.read({
keys: [...],
columns: [...],
toJSON: true
}, function(err, rows) {
var row = rows[0]
// row.Name = 'value'
})
```
```js
table.createReadStream({
keys: [...],
columns: [...],
toJSON: true
})
.on('data', row => {
// row.Name = 'value'
})
```
`row.toJSON()` supports options, such as `wrapNumbers`. To get these through, the user has to provide `toJSONOption: {...}` alongside `toJSON: true`.
> Support toJSON() on read methods.

- src/database.js
- src/partial-result-stream.js
- src/table.js
- src/transaction-request.js
- system-test/spanner.js
- test/database.js
- test/partial-result-stream.js
- test/transaction-request.js
The original PR, #94, made a poor choice in variable naming. We haven't released to npm, so we'd like to change the name before it's permanent.
Instead of:
```js
table.read({
keys: [...],
columns: [...],
toJSON: true
}, function(err, rows) {
var row = rows[0]
// row.Name = 'value'
})
```
This seems better:
```js
table.read({
keys: [...],
columns: [...],
json: true // <--
}, function(err, rows) {
var row = rows[0]
// row.Name = 'value'
})
```
> Rename `query.toJSON` to `query.json`.

- protos/google/spanner/v1/spanner.proto
- samples/batch.js
- samples/system-test/spanner.test.js
- src/batch-transaction.js
- src/codec.js
- src/database.js
- src/index.js
- src/transaction-request.js
- src/v1/spanner_client.js
- src/v1/spanner_client_config.json
- test/batch-transaction.js
- test/codec.js
- test/database.js
- test/index.js
- test/transaction-request.js
> feature: batch queries

- samples/crud.js
- samples/indexing.js
- samples/schema.js
- samples/transaction.js
- src/database.js
- src/instance.js
- src/table.js
Related
* GoogleCloudPlatform/ruby-docs-samples#244
* GoogleCloudPlatform/python-docs-samples#1376
* GoogleCloudPlatform/java-docs-samples#1045
* GoogleCloudPlatform/dotnet-docs-samples#454
* GoogleCloudPlatform/php-docs-samples#562
* GoogleCloudPlatform/golang-samples#403
> Cleanup Spanner region tags.

- protos/google/spanner/admin/database/v1/spanner_database_admin.proto
- protos/google/spanner/admin/instance/v1/spanner_instance_admin.proto
- protos/google/spanner/v1/keys.proto
- protos/google/spanner/v1/mutation.proto
- protos/google/spanner/v1/query_plan.proto
- protos/google/spanner/v1/result_set.proto
- protos/google/spanner/v1/spanner.proto
- protos/google/spanner/v1/transaction.proto
- protos/google/spanner/v1/type.proto
- src/v1/database_admin_client.js
- src/v1/doc/google/protobuf/doc_duration.js
- src/v1/doc/google/protobuf/doc_struct.js
- src/v1/doc/google/protobuf/doc_timestamp.js
- src/v1/doc/google/spanner/v1/doc_keys.js
- src/v1/doc/google/spanner/v1/doc_mutation.js
- src/v1/doc/google/spanner/v1/doc_query_plan.js
- src/v1/doc/google/spanner/v1/doc_result_set.js
- src/v1/doc/google/spanner/v1/doc_spanner.js
- src/v1/doc/google/spanner/v1/doc_transaction.js
- src/v1/index.js
- src/v1/instance_admin_client.js
- src/v1/spanner_client.js
- src/v1/spanner_client_config.json
- test/gapic-v1-database-admin.js
- test/gapic-v1-instance-admin.js
- test/gapic-v1.js
Regenerating GAPIC code for spanner, database admin and instance admin. I think it only contains docs and cosmetic changes. Also, added three auto-generated unit test files.
> Regenerate gapic

- src/database.js
- src/instance.js
- system-test/spanner.js
- test/database.js
- test/instance.js
Fixes #127 
This adds get-or-create behavior to database.get() and instance.get().
> Remove autoCreate for objects that return operations.

- samples/system-test/spanner.test.js
Test resources get deleted in the before hook and it appears as though deleting our instance in the after hook triggers an error somewhere.
https://circleci.com/gh/googleapis/nodejs-spanner/2886
> testing: remove samples after hook

- package.json
- samples/package.json
- samples/system-test/spanner.test.js
Since the problem of failing spanner tests was resolved in #148, the fix from #147 is not needed so let's put it back: we still want to delete our test data. Also, since we now allow multiple samples tests to run simultaneously (#149), we need to make sure that they are working with different instances, otherwise, when two CI tasks run simultaneously, the `before` hook of the second run will delete the instance that the first run is still using.
[Also, found out that we cannot just make the test run in parallel, as they depend on their order. Ideally, they should be rewritten :)]
> test: make sure tests can run in parallel

- system-test/spanner.js
The test `should get a session by name` always fails for me. Looks like the `session.metadata` is an empty object, but `.getMetadata()` resolves to a valid metadata that can be used for comparison. @callmehiphop, please review if the test fix looks good to you :)
> test: fix get session by name test

- src/table.js
the docs in the `Table` class seem to have a consistent mistake of referring to `instance.database` instead of `database.table` to create a table object. This PR corrects. If there's more to this, an issue can be opened instead.
> docs: fix table

- src/transaction.js
- test/transaction.js
This PR uses `protobufjs` to load a proto file instead of `grpc.load`.
See https://github.com/googleapis/nodejs-vision/pull/55 for context.
> refactor: use protobufjs library to load proto file

- src/session-pool.js
- test/session-pool.js
Fixes #173
In the event that the client is waiting for multiple sessions to free up, it was possible that we hit a race condition where the pool thought there were sessions available, when in fact there were not.
> fix(sessionPool): fix race condition

- package-lock.json
- package.json
- src/codec.js
- src/partial-result-stream.js
- src/row-builder.js
- system-test/spanner.js
- test/codec.js
- test/partial-result-stream.js
- test/row-builder.js
Fixes #180 and #198 by reworking the way we process streamed rows from PartialResultStream on Spanner. The high-level difference is this
1) use RowBuilder for all streams. We had two code paths previously
2) do not block on returning until we have a non-chunked row. We can hold the final value of a chunked segment and begin returning other data
3) handle partial segments. Occasionally we will get a partial row and shouldn't try to send that to the user.
> Rewrite PartialResultStream

- system-test/spanner.js
Use JSON.stringify when comparing query results.
Don't use stringify on the whole expected value, as that
does not work for nested arrays.
> test: fix strict equal assertions

- package.json
- src/database.js
Offers an alternative model to alleviate some of the issues in #249
> add runTransactionAsync method

- CHANGELOG.md
- package.json
- Drop support for Node.js v4.x.x and v9.x.x (#226) 
- Use es style imports (#302)
The import syntax for this library has changed to be [es module](https://nodejs.org/api/esm.html) compliant. 
```js
const spanner = require('@google-cloud/spanner')();
// or 
const Spanner = require('@google-cloud/spanner');
const spanner = new Spanner();
```
```js
const {Spanner} = require('@google-cloud/spanner');
const spanner = new Spanner();
```
- add runTransactionAsync method (#294)
```
const {Spanner} = require('@google-cloud/spanner');
const spanner = new Spanner();
const instance = spanner.instance('my-instance');
const database = instance.database('my-database');
await database.runTransactionAsync(async (transaction) => {
const [rows] = await …
```
> Release nodejs-spanner v2.0.0

- src/database.js
> Fix p-retry is accepting function not object/promise

- src/index.js
Let's wait for #301 to land first.
> chore: convert index to es6 class

- system-test/spanner.js
> soften assertion in system tests

- samples/quickstart.js
> Update QuickStart to use "new" syntax for creating Spanner client.

- samples/dml.js
- samples/system-test/spanner.test.js
> Add Cloud Spanner DML/PDML samples.

- samples/batch.js
- samples/crud.js
- samples/dml.js
- samples/indexing.js
- samples/schema.js
- samples/struct.js
- samples/system-test/spanner.test.js
- samples/timestamp.js
- samples/transaction.js
Fixes https://github.com/googleapis/google-cloud-node/issues/2869 (it's a good idea to open an issue first for discussion)
> docs(samples): updated samples code to use async await

- test/index.ts
- test/session-pool.ts
Seeing a number of TS related unit test failures since merging #400.
> test: fix ci/broken tests

- src/database.ts
- src/transaction.ts
- test/database.ts
- test/transaction.ts
> refactor(transaction): error handling

- src/transaction.ts
- test/transaction.ts
> fix(transaction): accept json options in run/runStream

- src/database.ts
- test/database.ts
Throw the full error in runTransactionAsync method instead of e.message.
**Issue:**
If you throw an error in the callback function, after a read for example, the error is misformatted.
**Example:**
```
await db.runTransactionAsync(async (transaction) => {
try {
const [[invoice: { status }]] = await transaction.read('Invoices', {
columns: ['status', 'invoiceId'],
keys: [invoiceId],
json: true,
});
if (status === "PAID") {
const error = new Error('Cannot update Invoice as it is already paid');
error.code = INVOICE_ALREADY_PAID
error.status = 403;
throw error;
}
// .......
await transaction.commit();
}
catch (err) {
// console.log(err.code) is undefined
// console.log(err.status) is undefined
next(err);
}
```
------
Also in version 2.1.0, Transaction.ABORTED is undefined in the error handler …
> fix transaction async error handling that not thrown the full error

- src/v1/database_admin_client.d.ts
- src/v1/index.d.ts
- src/v1/instance_admin_client.d.ts
- src/v1/spanner_client.d.ts
- tsconfig.json
While trying to chip away at improving types, I found myself defining a lot of request/response types and seeing a need for them across multiple files. I thought it might be useful to have definition files for our gapic clients (at least until we start generating them in TypeScript).
> chore(typescript): add types for spanner gapic

- src/database.ts
- src/transaction-runner.ts
- test/database.ts
- test/transaction-runner.ts
> fix(transaction): re-use session in transaction runners

- package.json
- src/batch-transaction.ts
- src/codec.ts
- src/index.ts
- src/transaction.ts
- system-test/spanner.ts
- test/batch-transaction.ts
- test/codec.ts
- test/index.ts
- test/transaction.ts
Fixes #494
Fixes #526 
Closes #529
---
This PR brings a new class for dealing with Cloud Spanner Timestamps. Previously we would return Date objects, but these were only good for millisecond precision. Since timestamps can come from the API in the form of either an ISO string or a protobuf timestamp, the class can handle either allowing users to easily use commit and read timestamps in queries, as well as result timestamps in snapshot bounds.
With ISO string.
```js
const timestamp = Spanner.timestamp('2019-02-08T10:34:29.481145231Z');
```
With protobuf timestamp.
```js
const [seconds, nanos] = process.hrtime();
const timestamp = Spanner.timestamp({seconds, nanos});
```
The Timestamp class extends the native Date class, so users can perform basic operations to the Timestamp if they choose. …
> feat(timestamp): create new date/timestamp classes

- src/index.ts
Fixes #604.
nodejs-spanner is not compiling for me, @JustinBeckwith is this being
looked at?
> fix(docs): add google.type namespace

- package.json
- samples/crud.js
- samples/dml.js
- samples/indexing.js
- samples/timestamp.js
- samples/transaction.js
- src/database.ts
- src/index.ts
- src/session-pool.ts
- test/session-pool.ts
> fix(deps): update dependency p-queue to v6.0.2

- src/session.ts
- system-test/spanner.ts
> refactor: enable noImplicitAny session.ts

- samples/datatypes.js
This change allows the `should use an ARRAY query parameter to query record from the Venues example table` test to pass when run on machines with time zones with positive offsets.
Fixes #710
> fix: don't wrap SpannerDate so timezone does not affect results

- src/index.ts
The createInstance() method should return a value to allow promise chaining.
Fixes #746.
> fix: createInstance should return a value

- samples/struct.js
- samples/system-test/spanner.test.js
- src/session-pool.ts
- test/session-pool.ts
The name of a `SessionLeakError` is set to `Error` by its super constructor. This makes checking specifically for a `SessionLeakError` more difficult.
Fixes #744
> fix: restore SessionLeakError name after super call

- src/session-pool.ts
The current stacktrace that is included in a `SessionLeakError` only contains the `_acquire` method itself, as the `_acquire` method calls an async method before getting the stacktrace. This change moves the call to get the caller stacktrace to the beginning of the method, which ensures that the stacktrace does contain the information that is needed.
This will also give us additional information that would be valuable to debug #716 
Fixes #755
> fix: get stacktrace before any async method call

- src/session-pool.ts
The error thrown by the session pool when it is exhausted should include the stacktraces of the checked out sessions. This information can be used to track down potential session leaks.
Fixes #758
> feat: include potential leaked session stacktraces in error

- samples/transaction.js
In the readWriteTransaction sample, if an error was thrown,
transaction.end() is now called so that the session is returned back to
the pool.
> fix: end read-write transaction in sample

- src/session-pool.ts
When a write-prepared session is returned to the session pool, a new read/write transaction will automatically be prepared for the session. The session stays in the `borrowed` set of the session pool inventory while the session is being prepared. The `_traces` entry for the session was however also kept while the session was being prepared. This would mark the session as leaked if the pool was closed before the `BeginTransaction` RPC had finished its execution. This is incorrect, as the session has been checked back into the pool by the application. Clearing the `_traces` entry for the session before starting the `BeginTransaction` RPC solves this.
[This test case](https://github.com/googleapis/nodejs-spanner/blob/840d9723cdd8cf71f9de083b426d83a0b44cd07a/test/spanner.ts#L144) would fail …
> fix: clear stack of session while preparing new r/w tx

- src/instance.ts
- test/instance.ts
`Instance.database(name, poolOptions)` should return different databases when called multiple times with the same name but with different pool options. Otherwise, the `SessionPoolOptions` supplied in the second and subsequent calls are not respected, and instead the options of the first call are used.
Fixes #753
> fix: return different databases for different pool options

- src/codec.ts
- test/codec.ts
Creating a SpannerDate with year/month/date values with year=0 would return an invalid date.
Fixes #782
> fix: year zero was not accepted for SpannerDate

- system-test/spanner.ts
Cloud Spanner could abort any read/write transaction, meaning that the number of attempts can always be higher than the minimum number of attempts expected.
Fixes #785
> chore(test): unflake transaction system tests

- src/transaction-runner.ts
- test/transaction-runner.ts
The transaction runner could timeout before the first transaction attempt had been executed, if a very short timeout value had been set. The transaction runner should always execute at least one transaction attempt before throwing a `DeadlineError`.
Fixes #786.
> fix: transaction runner should not timeout before first attempt

- src/session-pool.ts
- test/session-pool.ts
The session pool would always initiate the creation of a new session if one was not available at the moment that an application requested a session, even when a large number of sessions were already pending creation. This could cause the pool to create more sessions than necessary for an application.
Fixes #790.
> fix: session pool should only create session if pending<=waiters

- src/transaction-runner.ts
- test/transaction-runner.ts
The Node client did implement a client side backoff if no backoff information was provided by the server, but it did not maximize the fixed part of the backoff at 32 seconds. In addition, each backoff is added a randomized max 1 second jitter.
Fixes #653
> fix: fixed part of backoff should be between 1 and 32 seconds + max 1 second randomized jitter

- src/partial-result-stream.ts
- test/partial-result-stream.ts
The streaming call executeStreamingSql is not automatically retried by gax, as the gapic configuration for the call does not specify any error codes that should automatically be retried. Instead, the PartialResultStream is responsible for retrying these calls with the appropriate resume token. Until now, the call was only retried when a valid resume token had been seen for the stream, meaning that if the initial call failed with a retryable error code (e.g. UNAVAILABLE), the
stream would fail with this error. This fix ensures that the call is also retried when the error occurs for the initial call or before the stream has returned a valid resume token.
See also https://github.com/googleapis/nodejs-spanner/blob/09b5c56ed7844514283754235f7203364f01d6ab/test/spanner.ts#L199 for additional …
> fix: retry executeStreamingSql when error code is retryable

- src/database.ts
- test/database.ts
- test/mockserver/mockspanner.ts
- test/spanner.ts
If the `BeginTransaction` RPC of a read-only transaction fails with a 'Session not found' error, we can safely discard the invalid session, get a new session from the pool and retry the BeginTransaction call on the new session.
The session pool should normally keep all sessions alive by pinging them regularly with a simple SELECT 1, but it is known from other clients (Java, Go) that users can sporadically experience Session not found errors as sessions can be dropped by the backend. These clients have therefore added retry functionality for these errors.
> fix: retry 'Session not found' errors on getSnapshot

- src/database.ts
- src/session-pool.ts
- src/transaction-runner.ts
- test/mockserver/mockspanner.ts
- test/spanner.ts
Read/write transactions already automatically retry `ABORTED` errors. This PR extends the same retry logic to also retry `Session not found` errors.
> fix: retry 'Session not found' for r/w tx

- package.json
- test/database.ts
Remove @types/extend as it seems to be broken in combination with Node 12.16.0. `Object.assign(...)` can be used instead of extend. Only the deep copy option of extend is not natively supported by `Object.assign`.
Fixes #829
> deps: remove @types/extend

- proto/spanner.d.ts
- samples/queryoptions.js
- samples/system-test/spanner.test.js
- src/database.ts
- src/instance.ts
- src/session-pool.ts
- src/session.ts
- src/transaction-runner.ts
- src/transaction.ts
- src/v1/spanner_client.d.ts
- test/mockserver/mockspanner.ts
- test/spanner.ts
- test/transaction-runner.ts
- test/transaction.ts
Adds the ability to set `QueryOptions` when running Cloud Spanner queries. For now, only setting the `query_optimizer_version` is added.
QueryOptions can be configured through the following mechanisms:
1. Through the `SPANNER_OPTIMIZER_VERSION` environment variable.
1. At `Database` level using `spanner.instance('instance-name').database('database-name', sessionPoolOptions, queryOptions)`.
1. At query level using `ExecuteSqlRequest.queryOptions`.
If the options are configured through multiple mechanisms then:
1. Options set at an environment variable level will override options configured at the `Database` level.
1. Options set at a query-level will override options set at either the `Database` or environment variable level.
If no options are set, the optimizer version will default to:
1. …
> feat: add support for QueryOptions

- package.json
- src/backup.ts
- src/common.ts
- src/database.ts
- src/index.ts
- src/instance.ts
- system-test/spanner.ts
- test/database.ts
- test/index.ts
- test/instance.ts
- test/spanner.ts
> fix(types)!: properly format listing methods with gaxOptions

- .gitignore
- src/partial-result-stream.ts
- src/transaction.ts
- test/mockserver/mockspanner.ts
- test/partial-result-stream.ts
- test/spanner.ts
- test/transaction.ts
The request stream should be paused if the downstream is indicating that it cannot handle any more data at the moment. The request stream should be resumed once the downstream does accept data again. This reduces memory consumption and potentially out of memory errors when
a result stream is piped into a slow writer.
Fixes #934
> fix: pause request stream on backpressure

- samples/crud.js
- samples/system-test/spanner.test.js
[Docs](https://cloud.google.com/spanner/docs/modify-mutation-api#deleting_rows_in_a_table) list a set of dot points on the multiple ways to perform deletes. The updated samples now contain these examples.
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #1071 🦕
> fix: update DELETE samples to match docs

- src/index.ts
- test/spanner.ts
Previously if a display name was given, we were setting the instanceId to the display name. This is a bug.
Fixes #1093
> fix: set instanceId to the given id

- src/database.ts
When using `database.getSnapshot()`, it's invalid to set some of the
`TimestampBound` parameters since those can only be used for single-use
transactions.
> docs: explain invalid TimestampBounds params

- system-test/spanner.ts
Related to #1089, #1090, #1091 issues
Fixes #958
> chore: retry flaky tests for exceed administrative requests per minute quota error
