googleapis/nodejs-spanner

package.json
samples/package.json

Release notes forthcoming in the next comment.

Bump version to 0.8.0

---

samples/crud.js
samples/system-test/spanner.test.js

At the request of the spanner team.

Bump spanner stale read from 10 to 15 seconds.

---

.appveyor.yml
.circleci/config.yml
samples/crud.js
samples/indexing.js
samples/schema.js
samples/system-test/spanner.test.js
samples/transaction.js
src/transaction-request.js
src/transaction.js

RE: https://github.com/googleapis/nodejs-language/pull/24

Test on Node 9.

---

src/codec.js
src/database.js
src/transaction.js
test/codec.js
test/database.js
test/transaction.js

fix query param types bug

---

package.json
samples/package.json

bump version to 0.8.1

---

samples/crud.js
samples/system-test/spanner.test.js
samples/transaction.js
src/transaction-request.js

Since #52 got stalled on CI...

Linting per prettier@1.9.0.

---

src/transaction-request.js
system-test/spanner.js
test/transaction-request.js

do not promisify txn crud methods

---

src/index.js
test/index.js

Remove custom type instance methods.

---

package.json
src/database.js
src/session-pool.js
test/database.js
test/session-pool.js

track session leaks

---

src/transaction.js
test/transaction.js

Closes https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2644

increase transaction timeout

---

.circleci/config.yml

Making more repos run CI as non-root to avoid rebuilding grpc.

run CI as non-root user to speed up things

---

src/session-pool.js
system-test/spanner.js
test/session-pool.js

refactor acquire queuing

---

.cloud-repo-tools.json
.mailmap
CONTRIBUTORS
README.md
package.json
samples/crud.js
samples/indexing.js
samples/package.json
samples/schema.js
samples/transaction.js

- Spanner to GA!
- Samples fixes related to #80

release v1.0.0 to GA; fixing samples tests

---

src/session-pool.js
test/session-pool.js

fix session leak

---

src/database.js
test/database.js

format key when deleting cached database

---

samples/batch.js

Update region tags in Spanner batch sample.

---

samples/system-test/spanner.test.js

Fixes samples test command (https://circleci.com/gh/googleapis/nodejs-spanner/2859)

chore: remove dead tests

---

src/index.js
src/v1/spanner_client.js
system-test/spanner.js

feature: commit timestamp

---

package-lock.json
protos/google/spanner/v1/spanner.proto
protos/google/spanner/v1/type.proto
samples/package-lock.json
src/v1/doc/google/spanner/v1/doc_spanner.js
src/v1/spanner_client.js

Just a regular update of GAPIC `v1` generated code.

updating GAPIC v1 code

---

samples/system-test/spanner.test.js
samples/timestamp.js

Add Spanner commit timestamp sample.

---

src/database.js

docs(database): remove promise docs from runTransaction

---

src/session-pool.js
test/session-pool.js

test(sessionPool): check for out of bounds write value

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

- (#208): Fix how `PartialResultSet` are combined and iterated.

bump version to 1.4.2

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

- Retry on an additional error code, UNKNOWN, to lessen failures seen by users. (#202)

bump version to 1.4.3

---

src/codec.js
src/index.js
src/row-builder.js
system-test/spanner.js
test/codec.js
test/index.js

feat: struct query parameter

---

samples/struct.js
samples/system-test/spanner.test.js

Adding Spanner STRUCT param samples

---

.circleci/config.yml
package.json

fix: drop support for node.js 4.x and 9.x

---

package-lock.json
package.json
src/transaction.js
src/v1/database_admin_client.js
src/v1/doc/google/protobuf/doc_empty.js
src/v1/doc/google/spanner/v1/doc_type.js
src/v1/index.js
src/v1/instance_admin_client.js
src/v1/spanner_client.js
synth.py
test/transaction.js

Fixes #183 (it's a good idea to open an issue first for discussion)

add synth.py and generate

---

samples/system-test/spanner.test.js

Fix sample tests

---

CHANGELOG.md

Clearly not a very significant PR 😅 The devil is in the detail I guess

Fix color highlighting in CHANGELOG.md

---

system-test/spanner.js

fix string comparison in system test

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/spanner v2.2.0

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/spanner v2.2.1

---

CHANGELOG.md
package.json
samples/package.json

Add sample to delete using a mutation.
[ yes ] Tests and linter pass
[ NA ] Code coverage does not decrease (if any source code was changed)
[ NA ] Appropriate docs were updated (if necessary)

docs(samples): Add sample to delete using a mutation.

---

src/database.ts
src/table.ts
src/transaction-request.ts

docs: fix typo

---

src/table.ts
src/transaction-request.ts

docs: fix links in docstrings

---

package.json
scripts/cleanup.js
system-test/spanner.ts

Fixes [#2883](https://github.com/googleapis/google-cloud-node/issues/2883) (it's a good idea to open an issue first for discussion)

refactor: removed async from dependency list

---

src/table.ts

Fixed example for Table.upsert()

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/spanner v3.0.0

---

package.json
src/session-pool.ts
test/session-pool.ts

chore(deps): use bundled p-queue types

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/spanner v3.1.0

---

benchmark/ycsb.js

tests: correctly sort latencies

---

src/codec.ts
test/batch-transaction.ts
test/database.ts
test/session-pool.ts
test/transaction.ts

Fixes #542 
add tests to increase code coverage

tests: add tests to increase code coverage

---

samples/dml.js
samples/system-test/spanner.test.js

docs(samples): Add queryWithParameter to Cloud Spanner sample.

---

src/transaction.ts
test/transaction.ts

fix(transaction): set/update seqno for all sql requests

---

.gitignore
package.json

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕

chore: remove unused packages

---

src/database.ts
test/spanner.ts

The Database.run(query) method declared a return type of `Promise<Row[]>`, while its actual return type was `Promise<[Array<Row | Json>, ResultSetStats]>`.
Fixes #809

fix: fixed wrong return type of Database.run(..)

---

system-test/spanner.ts

Fixes #861
I believe the work in #855 left a lingering instance that had backups. Apparently, you have to delete the backups first before being allowed to delete the instance. We didn't think of that before, 'cause we didn't support backups. 
This should delete them in a verbose way for now, and then when we merge #855, we can simplify the code a bit.

test: delete backups before deleting instances

---

src/table.ts
src/transaction.ts

fix(types): fix type of ReadRequest

---

package.json
protos/protos.json
synth.metadata
synth.py

Run the latest version of the generator, update google-gax, update gts, and remove direct dependencies on eslint.

fix: remove eslint, update gax, fix generated protos, run the generator

---

samples/package.json

fix: update spanner package in sample

---

samples/system-test/spanner.test.js

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #954  🦕

fix: delete old instances then create new instance

---

system-test/spanner.ts

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #932 🦕

fix: skip some tests when run against the emulator

---

src/index.ts
test/index.ts

feat: expose displayName in createInstance

---

src/backup.ts
system-test/spanner.ts

- Re-use initially created `database` to lighten up the rate of Administrative requests
- Improve resources clean up to avoid exceeding nodes quota for a project

chore: improve system-tests

---

samples/package.json
samples/system-test/spanner.test.js

chore: improve samples-test

---

system-test/spanner.ts

fix: always clean up stale instances if any

---

src/backup.ts
test/backup.ts

feat: support callbacks for exists(), getState(), getExpireTime() methods

---

samples/instance.js
samples/system-test/spanner.test.js

feat: add code sample for creating an instance

---

src/backup.ts
test/backup.ts

chore: update backup module and backup unit tests

---

samples/instance.js

Also updated `nodes` to 1 to be consistent with other samples.

fix: set displayName in CreateInstance sample

---

.github/workflows/system-tests-against-emulator.sh
system-test/spanner.ts

Also running a previously skipped test against the emulator but still skipping it against prod.

fix: unskip PDML tests when run against emulator

---

samples/system-test/spanner.test.js
system-test/spanner.ts

chore(system/samples-test): lower the age of old instances to 4 hours

---

samples/crud.js

fix(samples-test): race condition in deleteData sample

---

samples/dml.js

Currently `should transfer value from one record to another using DML statements within a transaction` test throws an error ([link](https://source.cloud.google.com/results/invocations/81f776c0-1e79-4c92-a3d5-59094a889c93/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-spanner%2Fnode10%2Fsamples-test/log)) and does not "transfer value from one record to another ..." as it supposed to.

fix: race condition in "should transfer value from one record to another using DML statements within a transaction test"

---

samples/system-test/spanner.test.js

chore: create instance sample
